# Generated by Django 3.2.15 on 2022-10-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
            ],
            options={
                'db_table': 'problems',
            },
        ),
    ]
