# Generated by Django 3.2.15 on 2022-08-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Вариант ответа')),
                ('is_true', models.BooleanField(default=False, verbose_name='Правильный ответ')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_relation', to='hidden_app.answer', verbose_name='Ответ')),
                ('answer_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_relation2', to='hidden_app.answer', verbose_name='Ответ')),
                ('answer_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_relation3', to='hidden_app.answer', verbose_name='Ответ')),
                ('answer_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_relation4', to='hidden_app.answer', verbose_name='Ответ')),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
    ]
