# Generated by Django 3.2.15 on 2022-08-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='answer',
            new_name='answer_1',
        ),
    ]
