# Generated by Django 3.2.15 on 2022-08-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_app', '0002_rename_answer_quiz_answer_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Правильный ответ')),
            ],
            options={
                'db_table': 'info',
            },
        ),
    ]
