# Generated by Django 3.2.15 on 2022-09-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_app', '0003_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer_4',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
