# Generated by Django 3.2.15 on 2022-09-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_app', '0004_auto_20220924_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название конкурса')),
                ('document_name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
            ],
            options={
                'db_table': 'contest',
            },
        ),
        migrations.AlterField(
            model_name='info',
            name='text',
            field=models.TextField(verbose_name='Подробная информация'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название цеха'),
        ),
    ]
