# Generated by Django 3.2.15 on 2022-09-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_app', '0005_auto_20220924_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название документа'),
        ),
    ]
