# Generated by Django 3.2.15 on 2022-10-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_app', '0006_alter_contest_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('text', models.TextField(verbose_name='Информация о разделе')),
            ],
            options={
                'db_table': 'addinfo',
            },
        ),
    ]
